= Readme

== Australian Place Naming Principles Code Repository

This repository contains a web-based copy of Australian Place Naming Principles document, that defines and describes the principles by which Geographical Names should be given in Australia, published under the authority of the https://www.icsm.gov.au/[Intergovernmental Committee on Surveying & Mapping].

This repository contains the source code in https://asciidoc.org/[ASCIIDOC] files and replicates the content of the https://raw.githubusercontent.com/icsm-au/gn-principles/main/official-document/ICSM%20Australian%20Place%20Naming%20Principles.pdf[official document] in a web-friendly format. An online rendering is available at: https://icsm-au.github.io/gn-principles/doc.html


=== Contributions

We encourage contributions to this repository and the principles!

Please contribute by:

. Raising concerns/ideas with ICSM's Place Names Working Group via icsm@ga.gov.au
. Creating Issue tickets within this repository's https://github.com/icsm-au/gn-principles/issues[Issue Tracker]
// . Creating requests to absorb changes against the document source files via a https://github.com/icsm-au/gn-principles/pulls[Pull Request]. +
// The source files are in the link:document[`document/`] folder of this repository.

// _If creating Pull Requests is a new/unknown thing for you, please communicate with the contacts below for help._


=== Rights and License

The information in this repository is available for reuse under the https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International license], see the link:LICENSE[LICENSE] file for the deed.

&copy; Intergovernmental Committee on Surveying and Mapping, 2026


=== Contacts

For more information about this repository, contact:

*Queensland Place Names team* +
Spatial Information Branch, Georesources Division +
Queensland Department of Natural Resources and Mines, Manufacturing and Regional and Rural Development (NRMMRRD) +
QldPlaceNames@nrmmrrd.qld.gov.au

For technical implementation and data model questions please contact:

*Nicholas Car* +
https://kurrawong.ai[KurrawongAI] +
nick@kurrawong.ai +
_Contractor to NRMMRRD's Spatial Information group._


=== Document Generation

This document is developed using the https://asciidoc.org/[ASCIIDOC] document system used for many https://www.ogc.org/[OGC] and https://www.iso.org/home.html[ISO] standards. It essentially builds HTML or PDF documents from a series of text files (ending in `.adoc`), images, with certain styling conventions.

This repository automatically builds this document from the source files in the `document/` folder using the https://asciidoctor.org/[ASCIIDoctor] tool that it integrated into a GitHub Action, meaning the document is rebuild with every error-free update to the source files here.

The auto-built document is online at https://icsm-au.github.io/gn-principles/doc.html.