== Introduction

This document specifies how place names should be assigned to support safety, cultural sensitivity and inclusivity. It intends to help naming authorities to fulfil custodial responsibilities and enable a consistent national approach to the naming of places.

=== Relations to other standards

This document is intended to be used in conjunction with other documents / standards issued by the https://linked.data.gov.au/org/icsm[https://www.icsm.gov.au][Intergovernmental Committee on Surveying and Mapping (ICSM)], in particular those issued by the https://linked.data.gov.au/org/icsm-pnwg[ICSM's Place Names Working Group (PNWG)].

==== ANZ Geographical Naming

* https://linked.data.gov.au/def/gn[Geographical Names Model]
** This model specifies how place name information is to be structured for validation and data exchange
** When names created according to this document's principles are to be validated or exchanged, they MUST conform to the model
* https://linked.data.gov.au/def/gn-cm[Geographical Names Creation & Maintenance Standard]
** This standard describes the roles and tasks undertaken in ANZ with respect to geographical naming
** Tasks relating to geographical names created in accordance with these principles MUST align with those in the standard

==== International Geographical Naming

#TODO#

=== Document Structure

This Standard is structured in the following way:

[cols="1,2,6"]
|===
| # | Section | Purpose

| 1 | Abstract | Short Standard overview
| 2 | Metadata | Standard's identifying information
| 3 | Preamble | Resources for the effective use of this Standard
| 4 | Introduction | Background information about how and why this Standard was developed and the role it plays in relation to other standards
| 5 | Principles | The principles for Geographical Naming, identified and defined in this document
| | Bibliography | References cited in this document
|===
